### ISSUE TITLE
Will this integration enable Rome to format, lint .astro files?

### ISSUE THREAD

**Issue by eai04191** [astro-community/astro-rome#28]
Hello. I'm trying to use Astro for the first time. I considered using Rome because setting up ESlint and Prettier was troublesome.

When I search for "astro rome", it comes up immediately, so I tried it, but it didn't work as expected. (Simply, rome says `unhandled file type`.)

So I read the README carefully... and found the following sentence:

> The utility will now lint and format with [Rome](https://npmjs.org/rome) all of your JavaScript and TypeScript files, including CommonJS modules in the dist folder.

Does this sentence mean that the built files can be formatted for delivery optimization and not for a better development experience?
(yes i'm not good at english.)
Or is my configuration just wrong and does this allow linting or formatting the astro files?

Please excuse the elementary question. thanks,

**Comment by nikolaxhristov** [comment]
Rome only formats these files: 
![image](https://user-images.githubusercontent.com/90222871/226158213-de17a013-5464-4cdb-b894-118edc610131.png)

Hit me up on Discord and I'll help you setup prettier for Astro. nikolaxhristov#1833
