### ISSUE TITLE
Difference between rome cli usage

### ISSUE THREAD

**Issue by alexanderniebuhr** [astro-community/astro-rome#64]
I would like to know what would be the difference or advantage using this plugin vs rome cli tool?

**Comment by NikolaRHristov** [comment]
Ease of use, you don't have to configure the CLI and it's integrated with the Astro build process. You could also do the same with just running Rome on `package.json` build after `astro build`. Also, it was just a test to see if the https://github.com/Lightrix/files-pipe integration works well with other components. Quality of life improvement I guess.
