### ISSUE TITLE
Is this abandoned? NPM package repository source has changed

### ISSUE THREAD

**Issue by dmackinn** [astro-community/astro-rome#98]
I noticed that 
https://www.npmjs.com/package/astro-rome
is now pointing at
https://github.com/NikolaRHristov/astro-rome
and that the version numbers now differ.
Wondering why the source repository for the package registry has changed away from https://github.com/astro-community/astro-rome

**Comment by NikolaRHristov** [comment]
Hi, @dmackinn I deleted my NPM account and that remove all the packages. The new package is the same as the old, it's juts restoration and the new link is this https://www.npmjs.com/package/astro-rome, you can follow the issue on https://github.com/astro-community/astro-compress - https://github.com/astro-community/astro-compress/issues/163. These will soon be synchronized with the official astro-community one. I'm just waiting on some persmissions. It's the same package, same developer. :)

**Comment by dmackinn** [comment]
Ah, thanks for the update!
